apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: specific-tapir-nodejs 
  janus-idp.io/tekton: specific-tapir-nodejs
  backstage.io/kubernetes-id: specific-tapir-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: specific-tapir-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  